### ISSUE TITLE
The usage instructions are unclear

### ISSUE THREAD

**Issue by sourman** [more03625/loom-video-downloader#1]
I followed the README instructions to do
1. npm i
2. npm run dev
3. create POST request with loom URL
4. got 404 error
5. checked link is valid and does open in browser

**Comment by more03625** [comment]
Hi @sourman,
I have updated the readme file with more clearer description & also added a Postman request image to understand the working on the repo in more better way.

Please check it out & let me know if that works for you.

**Comment by sourman** [comment]
Perfect. The new clear instructions worked. Thanks @more03625

**Comment by more03625** [comment]
Thanks for the confirmation @sourman!
