### ISSUE TITLE
not downloading the video

### ISSUE THREAD

**Issue by hasantezcan** [more03625/loom-video-downloader#2]
![image](https://github.com/more03625/loom-video-downloader/assets/32804505/b2aee0db-a2fa-44df-815c-d4601ca89ed3)

**Comment by rahul-p-more** [comment]
Hello @hasantezcan,

Apologies for the delayed responses. I've addressed the issue mentioned earlier. It primarily stemmed from query parameters. To resolve this, I [implemented a function](https://github.com/more03625/loom-video-downloader/commit/6de94de0aa4dac9be22da4c7ef195ba0ed3209a6) to remove query parameters from the video URL. You should now be able to download Loom videos without any interruptions.
