### ISSUE TITLE
404

### ISSUE THREAD

**Issue by wanghaisheng** [more03625/loom-video-downloader#3]
https://www.loom.com/share/686218b3d2a14b6ea3ad07b6627818f8?sid=529194f2-355f-43a5-bcc4-29554eb52800

**Comment by wanghaisheng** [comment]
I  use a simple html file with 

```
  <form method="POST" action="http://localhost:8080/download-video">
    <label>Enter Video URL:</label>
    <input type="text" name="video_url">
    
    <button type="submit">Download</button>
  </form>
```
to call api

**Comment by more03625** [comment]
Hi @wanghaisheng ,
You are using the Node.js API the wrong way. Please go through the code Once Or You can directly refer to [this page to learn how to use that API with the form](https://chat.openai.com/share/38039453-35b4-4bf3-9ed9-78450c4f0ecd).

**Comment by wanghaisheng** [comment]
can  you jus give me screenshot  I cannot access the url

**Comment by more03625** [comment]
Hi @wanghaisheng,
The URL I added, can be viewed by anyone, not sure what is the issue. but no problem i am adding it here.

![image](https://github.com/more03625/loom-video-downloader/assets/25549118/ab21dece-6933-49a6-8c3b-664073131a52)
